import { Timestamp } from "firebase/firestore";

export interface Patient {
  id: string,
  
  address: string,
  age: number,
  age_of_husband: number,
  city: string,
  civil_status: string,
  contact_no: string,
  date_of_birth: Timestamp,
  family_history_allergy: boolean,
  family_history_asthma: boolean
  family_history_blood_disease: boolean,
  family_history_cancer: boolean,
  family_history_cleft_lip: boolean,
  family_history_cyst: boolean,
  family_history_diabetes: boolean,
  family_history_epilepsy: boolean,
  family_history_goiter: boolean,
  family_history_heart_disease: boolean,
  family_history_hyper_tension: boolean,
  family_history_lung_disease: boolean,
  family_history_mentally_retarded: boolean,
  family_history_myoma: boolean,
  family_history_pre_eclampsia: boolean,
  family_history_twins: boolean,
  family_history_uti: boolean,
  first_name: string,
  last_name: string,
  medical_history_allergy: Timestamp,
  medical_history_blood_disease: Timestamp,
  medical_history_convulsion: Timestamp,
  medical_history_cyst: Timestamp,
  medical_history_diabetes: Timestamp,
  medical_history_goiter: Timestamp,
  medical_history_heart_disease: Timestamp,
  medical_history_hypertension: Timestamp,
  medical_history_lung_disease: Timestamp,
  medical_history_myoma: Timestamp,
  medical_history_pre_eclampsia: Timestamp,
  medical_history_uti: Timestamp,
  occupation: string,
  occupation_of_husband: string,
  personal_social_env_history_alcohol: boolean,
  personal_social_env_history_cigarette: boolean,
  personal_social_env_history_drugs: boolean,
  religion: string,
  sex: string,
  state: string
}